version: "3.7"
services:
  bern:
    image: "train-station:latest"
    restart: unless-stopped
    depends_on:
      - pulsar
    ports:
      - "8081:8081"
    environment:
      - "PULSAR_SERVICE_URL=pulsar://pulsar:6650"
      - "CITY=Bern"
      - "HTTP_PORT=8081"
      - "CONNECTED_TO=Zurich,Geneva"

  zurich:
    image: "train-station:latest"
    restart: unless-stopped
    depends_on:
      - pulsar
    ports:
      - "8082:8082"
    environment:
      - "PULSAR_SERVICE_URL=pulsar://pulsar:6650"
      - "CITY=Zurich"
      - "HTTP_PORT=8082"
      - "CONNECTED_TO=Bern"

  geneva:
    image: "train-station:latest"
    restart: unless-stopped
    depends_on:
      - pulsar
    ports:
      - "8083:8083"
    environment:
      - "PULSAR_SERVICE_URL=pulsar://pulsar:6650"
      - "CITY=Geneva"
      - "HTTP_PORT=8083"
      - "CONNECTED_TO=Bern"

  pulsar:
    image: kafkaesqueio/pulsar:2.6.1_kesque_3_jdk11
    ports:
      - "8080:8080"
      - "6650:6650"
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"
